add book preview page (#158 and #160)
iTechLibrary/mimir pull request #181
Opened 2022-06-01 10:58 UTC by sabrina34352

![image_2022-06-01_20-00-52](https://user-images.githubusercontent.com/63979168/171437845-35a03778-2883-4117-b679-2561d278e413.png)

2022-06-01 13:22 UTC, mimirprjct requested changes

2022-06-01 13:22 UTC, mimirprjct commented on .env
> +POSTGRES_HOST=localhost
Please revert this. In the future, just don't commit this file

2022-06-01 13:22 UTC, mimirprjct commented on .vscode/settings.json
> +}
Please this mask (exclude) this file. Use `git config --global core.exludesfile` setting to add ignore pattern for `.vscode`.

2022-06-02 06:57 UTC, IvanUglovets commented on packages/frontapp/src/app/components/ListBooks/index.tsx
> +            item_id={item?.id}
use item.material.id here, because you need the id of the material, not its status

2022-06-02 08:36 UTC, IvanUglovets approved these changes

2022-06-03 06:38 UTC, IvanUglovets approved these changes

2022-06-06 05:36 UTC, unrealsolver approved these changes

2022-06-06 05:37 UTC, mimirprjct approved these changes

2022-06-06 06:55 UTC, merged