add prolongTime resolver
iTechLibrary/mimir pull request #183
Opened 2022-06-01 14:17 UTC by IvanUglovets

2022-06-01 16:46 UTC, x8er approved these changes

2022-06-06 05:39 UTC, unrealsolver requested changes

2022-06-06 05:39 UTC, unrealsolver commented on packages/apiserver/src/schema.graphql
> +  prolongClaimPeriod(input: ProlongTimeInput): BookUnionResult!
Should be moved to appropriate place

2022-06-14 07:39 UTC, sabrina34352 approved these changes

2022-06-14 10:12 UTC, merged