Feature/implement claim a book
iTechLibrary/mimir pull request #192
Opened 2022-06-07 07:25 UTC by IvanUglovets

![image](https://user-images.githubusercontent.com/82332668/172320609-fa3a075c-b87f-4c63-9928-c0dfdbda755a.png)
![image](https://user-images.githubusercontent.com/82332668/172320698-94889d8f-0d53-496a-bdf4-33613792bbbe.png)
![image](https://user-images.githubusercontent.com/82332668/172320889-013bc550-51c8-403d-9120-d8e4c0eb1938.png)

2022-06-07 11:23 UTC, x8er requested changes
⚠️Wrong approach to create clsoe button
![image](https://user-images.githubusercontent.com/29728314/172367364-c5b98a34-9f09-424e-a865-040e546c5e16.png)
⚠️Success.png and ClaimABook.png should be svg, as in figma

2022-06-07 11:23 UTC, x8er commented on packages/frontapp/src/app/components/BookInfo/index.tsx
>  }
A lot of props here. I guess, It will be better to replace it with one prop. And props interface rename to "IBookInfoProps"

2022-06-07 11:23 UTC, x8er commented on packages/frontapp/src/app/components/Modal/index.tsx
> +export default Modal;
Make it though https://ru.reactjs.org/docs/portals.html

2022-06-07 11:23 UTC, x8er commented on packages/frontapp/src/app/components/Button/index.tsx
> +  }
You can remove these styles for hover, ill add them soon

2022-06-07 11:23 UTC, x8er commented on packages/frontapp/src/app/components/Button/index.tsx
> +    }
These too

2022-06-08 08:29 UTC, unrealsolver approved these changes

2022-06-09 13:28 UTC, x8er approved these changes

2022-06-10 06:27 UTC, merged