Manager sidebar
iTechLibrary/mimir pull request #211
Opened 2022-06-15 14:07 UTC by lexussuxel

![image](https://user-images.githubusercontent.com/79334896/173847524-42f34225-6d39-4a97-af88-9ea6a03f9eee.png)
Create sidebar for manager according to Figma's design.

2022-06-18 15:29 UTC, x8er requested changes
Pls, reinstall project with versions node 16.15.1 and npm 8.11.0

2022-06-20 11:02 UTC, IvanUglovets approved these changes

2022-06-20 12:44 UTC, x8er approved these changes

2022-06-21 05:47 UTC, sabrina34352 approved these changes

2022-06-21 08:39 UTC, merged