Feature/search by name or author
iTechLibrary/mimir pull request #217
Opened 2022-06-21 10:06 UTC by IvanUglovets

![image](https://user-images.githubusercontent.com/82332668/174774546-992aff59-55b5-4c40-bfa5-0059537382c1.png)

2022-06-23 08:37 UTC, sabrina34352 approved these changes

2022-06-23 09:01 UTC, x8er requested changes

2022-06-23 09:01 UTC, x8er commented on packages/frontapp/src/app/types/materilsTypes.ts
> +}
You can just export necessary types from auto-generated client-types file.

2022-06-23 09:01 UTC, x8er commented on packages/frontapp/src/app/types/materilsTypes.ts
> +}
The same solution as for IMaterialState

2022-06-24 08:19 UTC, x8er requested changes

2022-06-24 08:19 UTC, x8er commented on packages/frontapp/src/app/types/materialsTypes.ts
> +}
Use Pick or Omit from already declared type in apollo-client/../generated/client.types.ts

2022-06-30 07:53 UTC, merged