Feat/donates list
iTechLibrary/mimir pull request #279
Opened 2022-07-15 09:48 UTC by sabrina34352

![image_2022-07-13_21-12-15](https://user-images.githubusercontent.com/63979168/179199002-90c7236f-9c4d-49f2-9bf1-602dd41fb1bc.png)
![image_2022-07-15_13-25-22](https://user-images.githubusercontent.com/63979168/179199038-58ecd94a-73f6-4bc1-b873-45b35fb7a91d.png)
![image_2022-07-13_21-12-29](https://user-images.githubusercontent.com/63979168/179199051-3c3a51d0-d908-4bb8-a1ca-fd67a12e4d19.png)

2022-07-19 08:16 UTC, x8er approved these changes

2022-07-19 08:16 UTC, x8er commented on packages/frontapp/src/app/models/helperFunctions/claimHistory.ts
> -
i think there is should be an empty row

2022-07-19 08:30 UTC, x8er requested changes

2022-07-19 10:50 UTC, sabrina34352 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/index.tsx
> +const DonateeName = styled.p`
nono, like a person who donates book is called donatee

2022-07-19 10:55 UTC, x8er commented on packages/frontapp/src/app/components/OneDonatedBookPreview/index.tsx
> +const DonateeName = styled.p`
well, may be you are right, but [here is](https://www.yourdictionary.com/donatee) another meaning. If i incorrect - resolve this conversation

2022-07-20 10:13 UTC, sabrina34352 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/index.tsx
> +const DonateeName = styled.p`
yes i will write Donator

2022-07-22 10:06 UTC, IvanUglovets approved these changes

2022-07-26 09:52 UTC, x8er commented on packages/frontapp/src/utils/routes.ts
> +  BOOK_PREVIEW = 'item',
would that be a problem?

2022-07-26 09:53 UTC, x8er approved these changes

2022-07-27 06:12 UTC, merged