feature/items list
iTechLibrary/mimir pull request #287
Opened 2022-07-19 14:55 UTC by IvanUglovets

![image](https://user-images.githubusercontent.com/82332668/179781508-4106ef6e-be4e-460f-bfb4-41c3464f0c0a.png)
![image](https://user-images.githubusercontent.com/82332668/179781595-557880f9-c924-4f54-9690-945631ee6a45.png)

2022-07-22 12:16 UTC, sabrina34352 approved these changes

2022-07-26 08:26 UTC, lexussuxel commented on packages/apiserver/src/resources/materials/material.resolver.ts
> +  @UseGuards(AuthGuard)
Don't use UseGuards(AuthGuard), it's global

2022-07-26 10:00 UTC, x8er requested changes

2022-07-26 10:00 UTC, x8er commented on packages/frontapp/src/app/pages/BookPreview.tsx
> +  const navigate = useNavigate();
you add this, but don't use

2022-07-26 10:44 UTC, IvanUglovets commented on packages/frontapp/src/app/components/BookCardExtended/index.tsx
> +}
this case it cannot be implemented via Pick or Omit

2022-07-27 06:10 UTC, sabrina34352 approved these changes

2022-07-27 10:04 UTC, x8er approved these changes

2022-07-27 10:19 UTC, x8er approved these changes

2022-07-27 10:31 UTC, merged