feat add chitai-gorod service
iTechLibrary/mimir pull request #308
Opened 2022-07-28 14:29 UTC by IvanUglovets

2022-07-29 07:53 UTC, x8er approved these changes

2022-07-29 09:57 UTC, unrealsolver requested changes

2022-07-29 09:57 UTC, unrealsolver commented on packages/metadata-service/src/readers/chitai-gorod.service/index.ts
> +import { Bundle } from '../ozby.service';
Please move this to some common type

2022-07-29 09:57 UTC, unrealsolver commented on packages/metadata-service/src/readers/chitai-gorod.service/index.ts
> +          referenceId: this.READER_ID,
This should be a unique id provided by chitai-gorod, not just a const. This `referenceId` is used keep a reference to provider's entity and also for unique identification.

2022-07-29 09:57 UTC, unrealsolver commented on packages/metadata-service/src/readers/chitai-gorod.service/index.ts
> +      referenceId: this.READER_ID,
Same as above - referenceId should be unique

2022-07-29 09:57 UTC, unrealsolver commented on packages/metadata-service/src/readers/reader.service.ts
> +      await this.db.logAccess(existing.id);
It's not really required to be awaited, because we don't use a result of the operation and we don't care about precision here.

2022-07-29 09:57 UTC, unrealsolver commented on packages/metadata-service/src/readers/reader.service.ts
> +        content = await this[arrayOfServices[i]].readData(isbn);
This uses sequential read instead of parallel - let's ignore it for today, but fix in the next PR.

2022-08-03 08:21 UTC, x8er approved these changes

2022-08-03 11:36 UTC, unrealsolver approved these changes

2022-08-04 05:08 UTC, sabrina34352 approved these changes

2022-08-04 07:46 UTC, merged