Feature: Search by user name
iTechLibrary/mimir pull request #318
Opened 2022-08-03 17:16 UTC by lexussuxel

![image](https://user-images.githubusercontent.com/79334896/182669112-a76bc021-3fe0-4026-9196-2bb02a765a0c.png)
![image](https://user-images.githubusercontent.com/79334896/182669325-0f2bad05-052d-4209-b330-25dcc4d4fc44.png)

2022-08-03 17:37 UTC, unrealsolver requested changes

2022-08-03 17:37 UTC, unrealsolver commented on packages/frontapp/src/app/components/SearchByUserName/index.tsx
> +        fill="#BDBDBD"
Please, use constants / ui-kit

2022-08-03 17:37 UTC, unrealsolver commented on packages/frontapp/src/app/components/SearchByUserName/index.tsx
> +const SearchByUserName = () => {
This looks like a pretty generic search components. It makes sense to refactor it and split into `SearchInput` and `SearchByWhatever`

2022-08-03 17:37 UTC, unrealsolver commented on packages/frontapp/src/app/components/SearchByUserName/index.tsx
> +      <InputSearch
Why does this components require so much wrapping? Why `Enter` keypress handling is not default behavior?

2022-08-03 17:37 UTC, unrealsolver commented on packages/frontapp/src/app/components/UserList/index.tsx
> +            name={person?.username || 'a'}
What does it mean?

2022-08-03 18:16 UTC, IvanUglovets commented on packages/apiserver/src/resources/persons/person.resolver.ts
> +          name: username ? `%${username}%` : '%',
It is bad practice.Please move this logic into a service, the resolver, like the controller, should remain as thin as possible

2022-08-03 18:18 UTC, IvanUglovets commented on packages/apiserver/src/resources/CurrentUserLocation.decorator.ts
> +    return location.id;
what is this decorator for?

2022-08-03 18:20 UTC, IvanUglovets commented on packages/frontapp/src/app/components/UserList/index.tsx
> +  const { searchReaders } = useAppSelector((state) => state.readers);
it is better to take the state from the redax above before useEffect, so the code looks more beautiful and readable

2022-08-03 18:23 UTC, IvanUglovets commented on packages/apiserver/src/resources/persons/person.resolver.ts
> +    const data = Person.createQueryBuilder('person')
you forget "await" :)

2022-08-03 18:46 UTC, IvanUglovets commented on packages/apiserver/src/resources/persons/person.resolver.ts
> +    const data = Person.createQueryBuilder('person')
also use the try{}catch{} construct because the application might crash(

2022-08-04 13:00 UTC, IvanUglovets approved these changes

2022-08-04 17:26 UTC, sabrina34352 approved these changes

2022-08-04 17:45 UTC, merged