Fixed bug #309, #320
iTechLibrary/mimir pull request #321
Opened 2022-08-08 06:10 UTC by sabrina34352

![image](https://user-images.githubusercontent.com/63979168/183350796-1d7c5ab7-42df-437d-a20d-e48a0f140555.png)
 ## and manager side accept and donate bug fixed

2022-08-08 07:12 UTC, IvanUglovets approved these changes

2022-08-08 08:04 UTC, x8er requested changes
Also pls check alerts which received from github actions

2022-08-08 08:04 UTC, x8er commented on packages/frontapp/src/app/components/DonateInfo/index.tsx
> +      />
No need to do like this

2022-08-09 08:31 UTC, IvanUglovets approved these changes

2022-08-09 13:59 UTC, unrealsolver approved these changes

2022-08-10 05:32 UTC, merged