Search by book or author for manager
iTechLibrary/mimir pull request #326
Opened 2022-08-08 12:37 UTC by lexussuxel

2022-08-09 08:35 UTC, IvanUglovets commented on packages/frontapp/src/app/components/SearchByBookOrAuthor/index.tsx
> +
this is a static variable, you can take it out of the component

2022-08-09 12:30 UTC, sabrina34352 requested changes

2022-08-09 12:30 UTC, sabrina34352 commented on packages/frontapp/src/app/components/ListAllItems/index.tsx
> +  console.log(searchMaterials);
unnecessary code

2022-08-09 13:57 UTC, unrealsolver approved these changes

2022-08-10 05:34 UTC, sabrina34352 approved these changes

2022-08-10 07:35 UTC, x8er approved these changes

2022-08-10 08:24 UTC, merged