Clean up warnings
iTechLibrary/mimir pull request #337
Opened 2022-08-10 18:48 UTC by lexussuxel

2022-08-11 08:07 UTC, x8er requested changes
I see that not all warnings were resolved. But be careful when resolving them, because useEffect or another hook must have an empty array (deps)

2022-08-11 10:40 UTC, unrealsolver requested changes

2022-08-11 10:40 UTC, unrealsolver commented on packages/frontapp/src/app/app.tsx
> +  }, [setIsShowScanner]);
I checked, that this is the most probably an error in eslint or somewhere else. We should not use hook setter as dependencies.

2022-08-11 10:40 UTC, unrealsolver commented on packages/frontapp/src/app/components/AskManagerForm/index.tsx
> +  }, [data, setActive, setSuccessModal]);
Again, no setters in dependencies.

2022-08-11 10:40 UTC, unrealsolver commented on packages/frontapp/src/app/components/BookInfo/index.tsx
> +  const handleChangeDeadline = (e: React.ChangeEvent<HTMLInputElement>) => {
Is it possible to remove type declaration completely here?

2022-08-11 10:40 UTC, unrealsolver commented on packages/frontapp/src/app/components/BookInfo/index.tsx
> +    parseInt(e.target.value) <= 0 && setNewDeadline(1);
```suggestion
    const value = parseInt(e.target.value);
    setNewDeadline(
      value > 31 ? 31 :
      value <= 0 ? 1 : value
    )
```

2022-08-12 15:10 UTC, x8er approved these changes

2022-08-13 10:37 UTC, sabrina34352 approved these changes

2022-08-17 10:59 UTC, unrealsolver requested changes

2022-08-17 10:59 UTC, unrealsolver commented on packages/frontapp/src/app/app.tsx
> +  }, [setIsShowScanner]);
Should not be required here.

2022-08-17 10:59 UTC, unrealsolver commented on packages/frontapp/src/app/components/AskManagerForm/index.tsx
> +  }, [data, setActive, setSuccessModal]);
I mean, we should NOT use setter functions in dependencies.

2022-08-20 09:54 UTC, x8er requested changes

2022-08-20 09:54 UTC, x8er commented on packages/frontapp/src/app/components/ClaimTable/index.tsx
> +                        alt={''}
maybe better replace it with `alt=""`

2022-08-20 09:54 UTC, x8er commented on packages/metadata-service/src/readers/db.service.ts
> +// };
If we don't use this might be better to just remove?

2022-08-20 09:54 UTC, x8er commented on packages/metadata-service/src/readers/ozby.service/index.ts
> +// };
the same as above

2022-11-17 10:22 UTC, ngame2011 commented
@unrealsolver It looks like these changes are no longer needed. If so, can we close this PR?

2022-11-17 10:51 UTC, unrealsolver commented
Let's move on

2022-11-17 10:51 UTC, closed without merging