Feature/user additional location
iTechLibrary/mimir pull request #366
Opened 2022-08-25 14:03 UTC by IvanUglovets

2022-08-26 13:34 UTC, x8er approved these changes

2022-08-30 10:22 UTC, unrealsolver requested changes

2022-08-30 10:22 UTC, unrealsolver commented on packages/apiserver/src/migrations/1661339543400-migrationMy.ts
> +}
Are there any reasons not to merge these migrations into one?
Also, could you use more sane name other than `migrationMy` please?

2022-08-30 15:25 UTC, lexussuxel commented on packages/frontapp/src/app/components/DonateBook/index.tsx
> +  const { locations } = useAppSelector((state) => state.user);
Why you use useAppSelector for user two times?

2022-08-30 15:28 UTC, lexussuxel commented on packages/frontapp/src/app/components/DropdownLocation/index.tsx
> +  height: 24px;
you can use fixed value xl_2

2022-08-30 15:31 UTC, lexussuxel commented on packages/frontapp/src/app/components/OneDonatedBookPreview/index.tsx
> +  console.log(lastStatus);
Remove this console.logs

2022-08-31 09:18 UTC, x8er approved these changes

2022-08-31 13:20 UTC, x8er requested changes

2022-08-31 13:20 UTC, x8er commented on packages/apiserver/src/app/app.module.ts
> +    // { provide: APP_GUARD, useClass: GrantGuard },
why?

2022-09-01 07:41 UTC, x8er approved these changes

2022-09-05 08:27 UTC, lexussuxel approved these changes

2022-09-05 09:19 UTC, merged