[323] Email service
iTechLibrary/mimir pull request #367
Opened 2022-08-26 13:13 UTC by x8er

closes #323

2022-08-29 12:16 UTC, unrealsolver requested changes

2022-08-29 12:16 UTC, unrealsolver commented on package.json
> +    "nodemailer": "^6.7.8",
Can we use a single version?

2022-08-29 12:16 UTC, unrealsolver commented on packages/email-service/src/app/app.service.ts
> +        text: 'Test message',
we can already make it more generic, by creating an `Email` type, which will encapsulate all email-related data (body, from, to, subj, etc). And email service should know as little as possible about books, overdues and donations.

2022-08-29 12:16 UTC, unrealsolver commented on packages/email-service/src/app/app.controller.ts
> +    const sentOk = await this.appService.sendOverdueNotify(receivers);
Generally, would approve your approach of having a separate service. But let's consider following changes - there is should be a some queue between BE app and a mail service. So BE could post emails to the queue and instantly receive 200 OK. Email service pulls emails from that queue and sends them in order. The queue could be part of email-service. (e.g. https://github.com/bee-queue/bee-queue)

2022-08-29 12:32 UTC, x8er commented on package.json
> +    "nodemailer": "^6.7.8",
yeah, why not

2022-09-06 14:06 UTC, sabrina34352 approved these changes

2022-09-07 12:46 UTC, merged