Fix/some problems with rerender
iTechLibrary/mimir pull request #370
Opened 2022-08-31 07:47 UTC by IvanUglovets

2022-08-31 09:24 UTC, x8er requested changes

2022-08-31 09:24 UTC, x8er commented on packages/frontapp/src/app/app.tsx
> +import React, { FC, useCallback, useState } from 'react';
no need to import whole React library

2022-08-31 09:24 UTC, x8er commented on packages/frontapp/src/app/components/MainComponent/index.tsx
> +import React, { FC, SetStateAction, useCallback } from 'react';
the same as above. You can just import the `memo` method and use it

2022-08-31 09:24 UTC, x8er commented on packages/frontapp/src/app/components/NotificationIcon/index.tsx
> +import React, { FC } from 'react';
the same as above

2022-08-31 09:24 UTC, x8er commented on packages/frontapp/src/app/components/SearchWrapper/index.tsx
> +import React, { FC } from 'react';
the same as above

2022-08-31 09:24 UTC, x8er commented on packages/frontapp/src/app/components/Sidebar/index.tsx
> +import React, { FC } from 'react';
the same as above

2022-09-01 07:41 UTC, x8er approved these changes

2022-09-05 08:22 UTC, lexussuxel approved these changes

2022-09-05 13:40 UTC, x8er approved these changes

2022-09-07 09:28 UTC, merged