fix undefined statuses (fix #409)
iTechLibrary/mimir pull request #438
Opened 2022-09-30 15:46 UTC by sabrina34352

this error happened, because the array of statuses was `[ ]`. this happens only to generated books, and as i understood never to added books, because person_id is added, and statuses can be created successfully. In order to fix this, i generate the first status and assigned this to person with `person_id 1` but the person_id should be manager's (like Ruslan's), when statuses are undefined, or of length zero, the buttons of claim or return do not appear. but after reloading page, the status gets created.

2022-10-07 10:55 UTC, unrealsolver requested changes
Please create a data migration for this issue. And make sure this will not happen in the future. BTW, what is 'generated' books?

2022-10-07 17:33 UTC, sabrina34352 commented
> 
generated book is the one created with 'npm run seed' to recreate status undefined problem i ran this command, and all the books had undefined statuses, so i thought that the one in production was generated as well

2022-10-11 09:44 UTC, IvanUglovets commented
yes, this problem is related to the books that were generated by the seeds. In this case, you just need to write a migration to a selection of books whose status history is empty and add an entry, for example, from (Alesya or Ruslan), that is, take their person_id. Or the second way out is to write a migration to delete books that have no status, since most likely they are not real, but mock

2022-10-14 08:46 UTC, unrealsolver approved these changes

2022-10-15 09:32 UTC, merged