fix: rename label (close #474)
iTechLibrary/mimir pull request #478
Opened 2022-11-05 15:38 UTC by vyacheslav1618

2022-11-06 10:45 UTC, vyacheslav1618 commented
![Снимок экрана 2022-11-05 190705](https://user-images.githubusercontent.com/78039218/200166334-59c78533-89ae-473f-b37f-cbea95ce624d.jpg)

2022-11-08 07:18 UTC, Chichmarin17 commented
Looks ok for me. But could you add screenshots as well as the `closes` label right into pr's description rather that comments?

2022-11-08 07:27 UTC, Chichmarin17 requested changes

2022-11-08 07:27 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/CategoriesList/index.tsx
> +        <Header>{t('Books')}</Header>
This translation won't work when you switch to Russian (check how we use translation in other components)

2022-11-08 07:27 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/CategoriesList/index.tsx
> +        <Header>{t('Other')}</Header>
Here as well

2022-11-08 11:04 UTC, Chichmarin17 approved these changes

2022-11-08 18:36 UTC, merged