adjust search filters
iTechLibrary/mimir pull request #479
Opened 2022-11-07 08:26 UTC by mabrur-h

Close #467 
![image](https://user-images.githubusercontent.com/52496254/200261579-4fcd6410-77b2-4e57-b471-9527f981c5d5.png)
![image](https://user-images.githubusercontent.com/52496254/200261607-264cc5ef-a09c-4528-abff-b83edb442dbe.png)

2022-11-08 07:40 UTC, Chichmarin17 requested changes
Can you adjust `back to all categories` button to match design as well?

2022-11-08 08:06 UTC, mabrur-h commented
> Can you adjust `back to all categories` button to match design as well?

Close #467
![image](https://user-images.githubusercontent.com/52496254/200508637-2c260d2b-890d-4f64-b318-41cb88f7a4e9.png)
![image](https://user-images.githubusercontent.com/52496254/200508680-26bbafa8-47e2-455b-bdd8-02aa33072191.png)

I added margin to the back button

2022-11-09 07:30 UTC, Chichmarin17 approved these changes

2022-11-11 07:17 UTC, sabrina34352 requested changes

2022-11-11 07:17 UTC, sabrina34352 commented on packages/frontapp/src/app/components/BooksByCategory/tags.tsx
>    font-size: 24px;
use `dimensions` toolkit variables

2022-11-11 07:17 UTC, sabrina34352 commented on packages/frontapp/src/app/components/BooksByCategory/tags.tsx
>    gap: 16px;
same thing

2022-11-16 12:02 UTC, sabrina34352 approved these changes

2022-11-16 12:02 UTC, sabrina34352 commented on packages/frontapp/src/app/components/BackButton/index.tsx
> +  margin-left: 18px;
do not forget to change them to dimesions.ts

2022-11-17 10:04 UTC, ngame2011 commented
@mabrur-h @Chichmarin17 what is the status of this PR now? I see that it is necessary to make minor changes and you can close this PR. 10 days for such changes is too long.

2022-11-17 11:39 UTC, mabrur-h commented
@ngame2011 I think we can close this PR. I have changed px to constant values.

2022-11-18 08:17 UTC, merged