add test and stories on Modal
iTechLibrary/mimir pull request #511
Opened 2022-11-21 14:17 UTC by vyacheslav1618

closes #506

test: close button check not finished
storybook: modal window not showing

2022-11-22 08:57 UTC, vyacheslav1618 commented
Modal hasn't a possibility to be written into StoryBook

whole of the tests are work

2022-11-23 07:46 UTC, Chichmarin17 requested changes

2022-11-23 07:46 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/Modal/index.stories.tsx
> +};
I can't see any content on Storybook when opening/closing a modal. Can you add some `children` to Modal e.g. a black square / text content ?

2022-11-23 07:46 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/Modal/index.stories.tsx
> +  //setActive: ;
Remove commented code

2022-11-28 10:20 UTC, vyacheslav1618 commented
There are some troubles with render Modal. Even though I try to set the "active" attribute to "true" or "false" it doesn't work. Modal component doesn't render. 
"Text for example #1" rendered. 
We need to refactor Modal completely and only then draw it up in the Storybook.

2022-11-29 07:52 UTC, Chichmarin17 commented
@vyacheslav1618 if you had checked how Modal works you would have noticed that it uses `React Portal`. That means, you have to add HTMLElement with `id` (`<div id='name_of_id'>`) that Modal uses to inject its content in. Also, change your `active` prop to use the Parent state

2022-11-30 07:51 UTC, Chichmarin17 approved these changes

2022-11-30 08:15 UTC, merged