add statistics button component
iTechLibrary/mimir pull request #531
Opened 2022-12-05 17:13 UTC by vyacheslav1618

closes #528 
![Снимок экрана от 2022-12-05 22-04-25](https://user-images.githubusercontent.com/78039218/205699380-dd392a7f-6a79-4e25-a211-a6d3bf833fae.png)
![Снимок экрана от 2022-12-05 22-05-54](https://user-images.githubusercontent.com/78039218/205699388-aa98ea7b-7b22-4730-bd35-790be106b3db.png)

There is no required SVG image in project library.

2022-12-05 17:39 UTC, vyacheslav1618 commented
![Снимок экрана от 2022-12-05 22-38-47](https://user-images.githubusercontent.com/78039218/205705009-4a1a3ef1-4820-4a24-8097-813098a96728.png)
![Снимок экрана от 2022-12-05 22-38-35](https://user-images.githubusercontent.com/78039218/205704975-f8f2992f-9906-4dcb-be2d-a5f3469193b7.png)

2022-12-06 11:02 UTC, Chichmarin17 requested changes

2022-12-06 11:02 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/SearchWrapper/index.tsx
> +        <>
why do we need that extra fragment wrapper?

2022-12-06 11:02 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/SearchWrapper/index.tsx
> +      <StatisticsButton />
We should not show the statistics button for readers, render it only for managers

2022-12-09 07:16 UTC, Chichmarin17 requested changes

2022-12-09 07:16 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/SearchWrapper/index.tsx
> +      {isReadersPage ? null : <StatisticsButton />}
You must check not `readers` page but a `manager` role

2022-12-12 11:17 UTC, ngame2011 approved these changes

2022-12-16 06:09 UTC, merged