Feature/456 load old pictures to digital ocean
iTechLibrary/mimir pull request #539
Opened 2022-12-20 08:30 UTC by Yoinezero

- Implement function to read file from .../storage/tmp
- Create NestJS Interceptor
  - Connect DigitalOceanService and FileService
  - Update Material with new url for picture
  - Remove physical file after update (5s)
- Use interceptor in resolvers for [Material]

2022-12-21 06:38 UTC, ngame2011 commented on packages/apiserver/src/resources/materials/material.interceptor.ts
> +              setTimeout(() => {
Suggestion: Let's remove `setTimeout` and do this callback inside one more `then` block:

```typescript
this.digitalOceanService.createFile({
   originalname: file.originalname,
   buffer: file.buffer,
})
.then(newName) => Material.update(item.id, { picture: newName.toString() }) )
.then(() => {
  this.fileService.removeFile(item.picture.split('/').pop());
});
```

2022-12-21 06:41 UTC, ngame2011 commented on packages/apiserver/src/resources/materials/material.interceptor.ts
> +export class TransformInterceptor<T> implements NestInterceptor<T, Material[]> {
Use a more descriptive class name so that it is clear what exactly it does

2022-12-21 06:55 UTC, ngame2011 commented on packages/helper-functions/src/lib/readLocalFile.ts
> +export const readLocalFile = (
This function doesn't look good - hardcoded values are used. We need to find another way to read files.

2022-12-21 06:56 UTC, ngame2011 requested changes
I don't quite understand why we can't do a migration that will migrate all the files in one go and not use a interceptor and other approaches?

2022-12-26 14:31 UTC, IAlexHilimovich commented on packages/apiserver/src/data-transfer/data-transfer.service.ts
> +      errors = 0;
Better declare each variable with its own `let`

2022-12-26 14:31 UTC, IAlexHilimovich commented on packages/apiserver/src/data-transfer/data-transfer.service.ts
> +  async move(): Promise<{ successes: number; errors: number }> {
I would create an interface for this type `{ successes: number; errors: number }`

2022-12-26 14:32 UTC, IAlexHilimovich commented on packages/apiserver/src/data-transfer/data-transfer.service.ts
> +        await deleteLocalFile(material.picture);
I would move this 4 lines to a separate method

2022-12-26 14:33 UTC, IAlexHilimovich commented on packages/apiserver/src/data-transfer/data-transfer.service.ts
> +        picture: Like(`%${process.env['NX_API_ROOT_URL']}%`),
First `%` is not necessary?

2022-12-26 14:34 UTC, IAlexHilimovich commented on packages/helper-functions/src/lib/file-system-services/deleteLocalFile.ts
> +};
Isn't it synchronous operation? Do you need promise here?

2022-12-26 14:36 UTC, IAlexHilimovich commented on packages/helper-functions/src/lib/file-system-services/deleteLocalFile.ts
> +        : reject(new UnknownFileError('Unknown error'));
What is the purpose of having different error types?

2022-12-26 14:37 UTC, IAlexHilimovich commented on packages/helper-functions/src/lib/file-system-services/readLocalFile.ts
> +};
Same as with delete
Also I would create normal Nestjs injectable service with read and delete methods

2022-12-27 06:23 UTC, IAlexHilimovich commented on packages/apiserver/src/data-transfer/data-transfer.controller.ts
> +  TransferData(): Promise<DataTransferOut> {
method names should be lower-case

2022-12-27 06:24 UTC, IAlexHilimovich commented on packages/apiserver/src/data-transfer/data-transfer.service.ts
> +  private async transferFile(material: Material) {
Please add return type

2022-12-27 06:27 UTC, IAlexHilimovich commented on packages/apiserver/src/file/file.service.ts
> +  async removeFile(fileUrl: string): Promise<void> {
As far as I can see, you can remove async and return `void`

2022-12-27 06:29 UTC, IAlexHilimovich commented on packages/apiserver/src/file/file.service.ts
> +  async readFile(fileUrl: string): Promise<File> {
Can remove async and return `File`

2022-12-27 06:30 UTC, IAlexHilimovich commented on packages/apiserver/src/file/file.service.ts
> +  private parseFileLocation(path): URL {
Add type for `path` input

2022-12-27 09:08 UTC, IAlexHilimovich approved these changes

2022-12-27 09:12 UTC, ngame2011 approved these changes

2022-12-27 09:14 UTC, merged